//import biriyaniImg from '../src/assets/images/styles/biriyani.png';
const list = [
    {
      id: 1,
      title: "Chicken Biriyani",
      price: 120,
      img: "http://sautefrynbake.com/wp-content/uploads/2016/10/IMG_1580-300x225.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "Coconutty Crispy Fried Prawns",
      price: 128,
      img: "http://www.sautefrynbake.com/wp-content/uploads/2014/10/image-73-300x225.jpeg",
      amount: 1,
    },
    {
      id: 3,
      title: "Crab Lollipop",
      price: 150,
      img: "http://sautefrynbake.com/wp-content/uploads/2016/12/FullSizeRender-62-300x225.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "Chicken Kofta Curry",
      price: 200,
      img: "http://www.sautefrynbake.com/wp-content/uploads/2014/06/esckc-300x225.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "Momo's",
      price: 109,
      img: "http://www.sautefrynbake.com/wp-content/uploads/2014/09/image30-300x225.jpeg",
      amount: 1,
    },
    {
      id: 6,
      title: "Channa Pulao",
      price: 135,
      img: "http://sautefrynbake.com/wp-content/uploads/2013/11/channa-300x225.png",
      amount: 1,
    },
    {
      id: 7,
      title: "Black Forest Shots",
      price: 253,
      img: "http://sautefrynbake.com/wp-content/uploads/2016/12/FullSizeRender-9-300x225.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "Bread Cones",
      price: 289,
      img: "http://sautefrynbake.com/wp-content/uploads/2015/04/image111-300x225.jpeg",
      amount: 1,
    },
    {
      id: 9,
      title: "Carrot Kheer",
      price: 80,
      img: "http://sautefrynbake.com/wp-content/uploads/2016/03/IMG_5909-300x195.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "Fish Pickle",
      price: 86,
      img: "http://www.sautefrynbake.com/wp-content/uploads/2013/11/fish-300x225.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "Vadai Kachubar Chat",
      price: 120,
      img: "http://sautefrynbake.com/wp-content/uploads/2015/06/image1-7-300x225.jpeg",
      amount: 1,
    },
    {
      id: 12,
      title: "Sulaimaani Tea",
      price: 157,
      img: "http://sautefrynbake.com/wp-content/uploads/2017/04/FullSizeRender-1-300x251.jpg",
      amount: 1,
    },
  ];
  export default list;